//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesMemorama
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartasJuego
    {
        public string id_Partida { get; set; }
        public int id_Imagen { get; set; }
        public int posicionCarta1 { get; set; }
        public string estadoCarta1 { get; set; }
        public int posicionCarta2 { get; set; }
        public string estadoCarta2 { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
