//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMemorama.ConexionServicio1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosUsuario", Namespace="http://schemas.datacontract.org/2004/07/ServicioMemorama")]
    [System.SerializableAttribute()]
    public partial class DatosUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConexionServicio1.IServicioUsuarios", CallbackContract=typeof(ClienteMemorama.ConexionServicio1.IServicioUsuariosCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServicioUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorSesion", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorSesionResponse")]
        int ConexionServidorSesion(ClienteMemorama.ConexionServicio1.DatosUsuario inicioUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorSesion", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorSesionResponse")]
        System.Threading.Tasks.Task<int> ConexionServidorSesionAsync(ClienteMemorama.ConexionServicio1.DatosUsuario inicioUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorRegistro", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorRegistroResponse")]
        bool ConexionServidorRegistro(ClienteMemorama.ConexionServicio1.DatosUsuario registroUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorRegistro", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorRegistroResponse")]
        System.Threading.Tasks.Task<bool> ConexionServidorRegistroAsync(ClienteMemorama.ConexionServicio1.DatosUsuario registroUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorCodigo", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorCodigoResponse")]
        string ConexionServidorCodigo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionServidorCodigo", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionServidorCodigoResponse")]
        System.Threading.Tasks.Task<string> ConexionServidorCodigoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuariosCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ConexionClienteSesion", ReplyAction="http://tempuri.org/IServicioUsuarios/ConexionClienteSesionResponse")]
        string ConexionClienteSesion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/ResultadoConexionSesion", ReplyAction="http://tempuri.org/IServicioUsuarios/ResultadoConexionSesionResponse")]
        void ResultadoConexionSesion(bool resultado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuariosChannel : ClienteMemorama.ConexionServicio1.IServicioUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuariosClient : System.ServiceModel.DuplexClientBase<ClienteMemorama.ConexionServicio1.IServicioUsuarios>, ClienteMemorama.ConexionServicio1.IServicioUsuarios {
        
        public ServicioUsuariosClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int ConexionServidorSesion(ClienteMemorama.ConexionServicio1.DatosUsuario inicioUsuario) {
            return base.Channel.ConexionServidorSesion(inicioUsuario);
        }
        
        public System.Threading.Tasks.Task<int> ConexionServidorSesionAsync(ClienteMemorama.ConexionServicio1.DatosUsuario inicioUsuario) {
            return base.Channel.ConexionServidorSesionAsync(inicioUsuario);
        }
        
        public bool ConexionServidorRegistro(ClienteMemorama.ConexionServicio1.DatosUsuario registroUsuario) {
            return base.Channel.ConexionServidorRegistro(registroUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> ConexionServidorRegistroAsync(ClienteMemorama.ConexionServicio1.DatosUsuario registroUsuario) {
            return base.Channel.ConexionServidorRegistroAsync(registroUsuario);
        }
        
        public string ConexionServidorCodigo(string correo) {
            return base.Channel.ConexionServidorCodigo(correo);
        }
        
        public System.Threading.Tasks.Task<string> ConexionServidorCodigoAsync(string correo) {
            return base.Channel.ConexionServidorCodigoAsync(correo);
        }
    }
}
